spring.application.name=orderservice

server.port=8083

spring.datasource.url=jdbc:postgresql://localhost:5432/Order_Service
spring.datasource.username=postgres
spring.datasource.password={$PASSWORD_DB:64190507SDv}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

services.user-service-url=http://localhost:8082

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8080/realms/payment-system